### PR TITLE
#195: RIPE SDK compatibility with Nuxt.js under Vercel

### LINKED ISSUE #195: RIPE SDK not compatible with Nuxt.js under Vercel
## Description

It's not possible to use the RIPE SDK with Nuxt.js when building the application with `--standalone`, which is [done by Vercel](https://vercel.com/platforme/epir-papyrus/n86vn2j95). Accessing the page where RIPE SDK is imported results in:

```
 ERROR  window is not defined                                                                                                                                                                                                                                                            09:18:03

  at Object.<anonymous> (node_modules/ripe-sdk/src/js/base/compat.js:83:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (node_modules/ripe-sdk/src/js/base/api.js:11:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (node_modules/ripe-sdk/src/js/base/index.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (node_modules/ripe-sdk/src/js/api/account.js:9:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (node_modules/ripe-sdk/src/js/api/index.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)


 ERROR  Cannot read property 'a' of undefined                                                                                                                                                                                                                                            09:18:03

  at Module.ReportHermesLeatherGoods (pages/hermes_leather.js:11360:145)
  at c (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at Tt (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at Function.Cn.t.extend (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at sanitizeComponent (.nuxt/utils.js:74:0)
  at server.js:14522:41
  at async Promise.all (index 0)
  at async getRouteData (.nuxt/utils.js:131:0)
  at async Promise.all (index 0)
  at async setContext (.nuxt/utils.js:214:0)
```

This is caused by the "environment" detection [part](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/compat.js#L57) not being ready to this use case:

```
if (
    typeof require !== "undefined" &&
    (typeof window === "undefined" || typeof __webpack_require__ !== "undefined") && // eslint-disable-line camelcase
    typeof XMLHttpRequest === "undefined" // eslint-disable-line no-use-before-define
) {
    var XMLHttpRequest = null;
    if (
        // eslint-disable-next-line camelcase
        typeof __webpack_require__ === "undefined" &&
        (typeof navigator === "undefined" || navigator.product !== "ReactNative")
    ) {
        // this is an hack to work around metro's (react-native bundler)
        // static analysis, needed until it supports optional imports
        // (https://github.com/react-native-community/discussions-and-proposals/issues/120)
        const mixedModuleName = "Xmlhttprequest";
        const correctModuleName = mixedModuleName.toLowerCase();
        XMLHttpRequest = require(correctModuleName).XMLHttpRequest;
    } else {
        XMLHttpRequest = window.XMLHttpRequest;
    }
}
```

The values at play here are:
- `require` is defined
- `__webpack_require__` is defined
- `window` is **NOT** defined
- `XMLHttpRequest` is **NOT** defined

Even though `require` is available and would be able to import `XMLHttpRequest`, the code is ending up in `XMLHttpRequest = window.XMLHttpRequest;` which throws an error.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Be able to import RIPE SDK. |
| **Observed** | Importing RIPE SDK throws an error. |

## Repro Steps

1. Using Nuxt.js, import RIPE SDK in one of the components
2. Build the application with `nuxt build --standalone`
3. Serve the generated files with `nuxt start`
4. Make a request to the page where RIPE SDK is being imported

### PR DESCRIPTION
**Pull request by BeeMargarida**
| - | - |
| --- | --- |
| Issue | Closes #195 |
| Dependencies | -- |
| Decisions | Checks to see if it is using webpack and the window is not defined. If so, uses the npm packages. Uses `__non_webpack_require__` to import `xmlhttprequest`, which is not defined by the `webpack's require`. This allows for no configuration in the `ripe-sdk`'s clients, as well as almost no changes in the existing code. |
| References |  • https://github.com/webpack/webpack/issues/11455 <br> • https://stackoverflow.com/questions/46185302/non-webpack-require-is-not-defined <br> • https://stackoverflow.com/questions/42797313/webpack-dynamic-module-loader-by-require | 
| Animated GIF | `epir-papyrus` with sdk, build with `nuxt build --standalone` and `nuxt start`: <br> Sep-28-2020 13-27-37 |

### CODE REVIEW

**Comment by BeeMargarida** [comment]
@gcandal The solution found has a drawback, which is the need to add the config in the description to `epir-papyrus` and other services that use nuxt and the sdk. 
Another option would be to not use the `xmlhttprequest`, by removing the added conditional, and only use `fetch`.

**Comment by BeeMargarida** [comment]
@gcandal I ended up finding a solution [here](https://github.com/webpack/webpack/issues/11455) and [here](https://stackoverflow.com/questions/46185302/non-webpack-require-is-not-defined). This (using `__non_webpack_require__`) was the solution that allowed no `try-catch` modules, no changes in the existing code and no configuration in `ripe-sdk` clients.

File: src/js/base/compat.js [hunk 1]
```diff
@@ -90,9 +97,12 @@ if (
...
         (typeof navigator === "undefined" || navigator.product !== "ReactNative")
     ) {
-        fetch = require("node-fetch");
-    } else {
+        fetch = require("node-fetch").default;
+    } else if (typeof window !== "undefined") {
         fetch = window.fetch;
+        // eslint-disable-next-line camelcase
+    } else if (typeof __webpack_require__ !== "undefined") {
+        fetch = require("node-fetch").default;
```
Comment (gcandal) [inline src/js/base/compat.js:105]: __webpack_require__

File: src/js/base/compat.js [hunk 2]
```diff
@@ -71,8 +71,15 @@ if (
...
         const correctModuleName = mixedModuleName.toLowerCase();
         XMLHttpRequest = require(correctModuleName).XMLHttpRequest;
-    } else {
+    } else if (typeof window !== "undefined") {
         XMLHttpRequest = window.XMLHttpRequest;
+        // eslint-disable-next-line camelcase
+    } else if (typeof __webpack_require__ !== "undefined") {
+        // using a plain require call to load the module, since using
+        // the webpack call will result in module not found by nuxt.js
+        // applications
```
Comment (gcandal) [inline src/js/base/compat.js:80]: Let's keep it nuxt-agnostic
```suggestion
        // use a runtime 'require' call that is
        // not parsed by webpack
```

File: src/js/base/compat.js (hunk 1 above)
Comment (gcandal) [inline src/js/base/compat.js:105]: replicate the comment

**Review by gcandal — CHANGES_REQUESTED** [review]

File: src/js/base/compat.js (hunk 1 above)
Comment (BeeMargarida) [reply src/js/base/compat.js:105]: @gcandal Do you mean doing `fetch = __webpack_require__("node-fetch").default;`?

Comment (gcandal) [reply src/js/base/compat.js:104]: yup!

**Review by gcandal — APPROVED** [review]

**Review by joamag — APPROVED** [review]
